import type { Scene } from './types'

export const scenes: Scene[] = [
  {
    id:          'gotham-city',
    title:       'GOTHAM CITY',
    subtitle:    'A city built on fear.',
    archiveCode: 'ARCHIVE 01 / 04',
    location:    'GOTHAM CITY — UPTOWN',
    background:  '/images/balcon-rejas.png',
    nextScene:   'crime-alley',
    prevScene:   null,
    hotspots: [
      {
        id:             'enter-city',
        area:           { top: 30, left: 35, width: 30, height: 40 },
        label:          'ENTER CITY',
        action:         'ENTER',
        targetScene:    'crime-alley',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'crime-alley',
    title:       'CRIME ALLEY',
    subtitle:    'Every city has a wound.',
    archiveCode: 'ARCHIVE 02 / 04',
    location:    'PARK ROW — EAST GOTHAM',
    background:  '/images/cartel-crime-alley.png',
    nextScene:   'the-incident',
    prevScene:   'gotham-city',
    hotspots: [
      {
        id:             'investigate-location',
        area:           { top: 25, left: 20, width: 60, height: 55 },
        label:          'INVESTIGATE LOCATION',
        action:         'INVESTIGATE',
        targetScene:    'the-incident',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'the-incident',
    title:       'THE INCIDENT',
    subtitle:    'Some stories begin with a tragedy.',
    archiveCode: 'ARCHIVE 03 / 04',
    location:    'CRIME ALLEY — PARK ROW',
    background:  '/images/rosas-calle.png',
    nextScene:   'the-archives',
    prevScene:   'crime-alley',
    hotspots: [
      {
        id:             'view-archive',
        area:           { top: 40, left: 30, width: 40, height: 40 },
        label:          'VIEW ARCHIVE RECORD',
        action:         'VIEW',
        targetScene:    'the-archives',
        transitionType: 'memory',
      },
    ],
  },
  {
    id:          'the-archives',
    title:       'THE ARCHIVES',
    subtitle:    'Classified records. Restricted access.',
    archiveCode: 'ARCHIVE 04 / 04',
    location:    'GOTHAM INTELLIGENCE NETWORK',
    background:  '/images/calle-autos.png',
    nextScene:   null,
    prevScene:   'the-incident',
    hotspots: [],
  },
  {
    id:          'crime-alley-investigation',
    title:       'CRIME ALLEY — INVESTIGATION',
    subtitle:    'Find the evidence. Close the case.',
    archiveCode: 'FILE 001',
    location:    'PARK ROW — ACTIVE INVESTIGATION',
    background:  '/images/frente-crime-alley.png',
    nextScene:   null,
    prevScene:   'the-archives',
    hotspots: [],
  },
  {
    id:          'arkham-investigation',
    title:       'ARKHAM ASYLUM',
    subtitle:    'The city locks away its monsters here.',
    archiveCode: 'FILE 002',
    location:    'ARKHAM ISLAND — RESTRICTED',
    background:  '/images/arkham-entrada.png',
    nextScene:   null,
    prevScene:   'the-archives',
    hotspots: [],
  },
  // ─── Arkham Asylum sequence (FASE 8) ────────────────────────────────────────
  {
    id:          'arkham-entrada',
    title:       'ARKHAM ASYLUM',
    subtitle:    'Some doors should never be opened.',
    archiveCode: 'SECTOR A',
    location:    'ARKHAM ISLAND — PERIMETER',
    background:  '/images/arkham-entrada.png',
    nextScene:   'arkham-fachada',
    prevScene:   'the-archives',
    hotspots: [
      {
        id:             'approach-building',
        area:           { top: 20, left: 20, width: 60, height: 60 },
        label:          'APPROACH',
        action:         'ENTER',
        targetScene:    'arkham-fachada',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'arkham-fachada',
    title:       'ARKHAM ASYLUM',
    subtitle:    'Built to contain the uncointainable.',
    archiveCode: 'SECTOR B',
    location:    'ARKHAM ISLAND — MAIN GATE',
    background:  '/images/arkham-fachada.png',
    nextScene:   'arkham-atrio',
    prevScene:   'arkham-entrada',
    hotspots: [
      {
        id:             'enter-building',
        area:           { top: 20, left: 20, width: 60, height: 60 },
        label:          'ENTER',
        action:         'ENTER',
        targetScene:    'arkham-atrio',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'arkham-atrio',
    title:       'ARKHAM ASYLUM',
    subtitle:    'Silence broken only by echoes.',
    archiveCode: 'SECTOR C',
    location:    'ARKHAM ISLAND — MAIN ATRIUM',
    background:  '/images/arkham-atrio.png',
    nextScene:   'arkham-puertas',
    prevScene:   'arkham-fachada',
    hotspots: [
      {
        id:             'access-records',
        area:           { top: 20, left: 20, width: 60, height: 60 },
        label:          'ACCESS RECORDS',
        action:         'INVESTIGATE',
        targetScene:    'arkham-puertas',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'arkham-puertas',
    title:       'CLASSIFIED RECORDS',
    subtitle:    'Abandoned government vault. Everything redacted.',
    archiveCode: 'FILE 002-A',
    location:    'ARKHAM ISLAND — RECORDS VAULT',
    background:  '/images/arkham-puertas.png',
    nextScene:   'arkham-intensivo',
    prevScene:   'arkham-atrio',
    hotspots: [],
  },
  {
    id:          'arkham-intensivo',
    title:       'INTENSIVE TREATMENT',
    subtitle:    'Wing B. Do not enter without escort.',
    archiveCode: 'FILE 002-B',
    location:    'ARKHAM ISLAND — WING B',
    background:  '/images/arkham-intensivo.png',
    nextScene:   'arkham-lunatico',
    prevScene:   'arkham-puertas',
    hotspots: [],
  },
  {
    id:          'arkham-lunatico',
    title:       'PATIENT DATABASE',
    subtitle:    'They are still in there. Some of them.',
    archiveCode: 'FILE 002-C',
    location:    'ARKHAM ISLAND — SECURE DATABASE',
    background:  '/images/arkham-lunatico.png',
    nextScene:   null,
    prevScene:   'arkham-intensivo',
    hotspots: [],
  },
  // ─── Wayne Tower sequence (FASE 8) ──────────────────────────────────────────
  {
    id:          'wayne-exterior',
    title:       'WAYNE TOWER',
    subtitle:    'The empire built on Gotham\'s grief.',
    archiveCode: 'SECTOR W-1',
    location:    'WAYNE ENTERPRISES — MIDTOWN',
    background:  '/images/wayne-tower.png',
    nextScene:   'wayne-lobby',
    prevScene:   'the-archives',
    hotspots: [
      {
        id:             'enter-tower',
        area:           { top: 20, left: 20, width: 60, height: 60 },
        label:          'ENTER TOWER',
        action:         'ENTER',
        targetScene:    'wayne-lobby',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'wayne-lobby',
    title:       'WAYNE ENTERPRISES',
    subtitle:    'Innovation for Gotham.',
    archiveCode: 'SECTOR W-2',
    location:    'WAYNE TOWER — GROUND FLOOR',
    background:  '/images/wayne-lobby.png',
    nextScene:   'wayne-sala',
    prevScene:   'wayne-exterior',
    hotspots: [
      {
        id:             'access-executive',
        area:           { top: 20, left: 20, width: 60, height: 60 },
        label:          'EXECUTIVE FLOOR',
        action:         'ACCESS',
        targetScene:    'wayne-sala',
        transitionType: 'archive',
      },
    ],
  },
  {
    id:          'wayne-sala',
    title:       'EXECUTIVE OPERATIONS',
    subtitle:    'Decisions made here shape the city.',
    archiveCode: 'SECTOR W-3',
    location:    'WAYNE TOWER — FLOOR 38',
    background:  '/images/wayne-sala.png',
    nextScene:   'wayne-despacho',
    prevScene:   'wayne-lobby',
    hotspots: [],
  },
  {
    id:          'wayne-despacho',
    title:       'BRUCE WAYNE OFFICE',
    subtitle:    'A room with two identities.',
    archiveCode: 'SECTOR W-4',
    location:    'WAYNE TOWER — FLOOR 42',
    background:  '/images/wayne-despacho.png',
    nextScene:   null,
    prevScene:   'wayne-sala',
    hotspots: [],
  },
  {
    id:          'batcomputer',
    title:       'BATCOMPUTER',
    subtitle:    'Wayne Network — Secure Intelligence Hub.',
    archiveCode: 'SYSTEM CORE',
    location:    'BATCAVE — EYES ONLY',
    background:  '/images/batcomputer-hub.png',
    nextScene:   'batcomputer-control',
    prevScene:   null,
    hotspots: [],
  },
  {
    id:          'batcomputer-control',
    title:       'CONTROL CENTER',
    subtitle:    'All of Gotham. Under surveillance.',
    archiveCode: 'SYSTEM CC-01',
    location:    'BATCAVE — OPERATIONS',
    background:  '/images/batcomputer-sala.png',
    nextScene:   null,
    prevScene:   'batcomputer',
    hotspots: [],
  },
]

export const getSceneById = (id: string): Scene | undefined =>
  scenes.find(s => s.id === id)
